package com.fintech.sre.agent.incident;

public enum IncidentStatus {
	DETECTED,
	RECOMMENDATION_CREATED,
	HUMAN_REVIEW_REQUIRED,
	ACTION_APPROVED,
	ACTION_REJECTED,
	OUTCOME_REPORTED,
	POSTMORTEM_DRAFT_READY,
	IMPROVEMENT_CANDIDATES_CREATED,
	KNOWLEDGE_REVIEW_REQUESTED,
	CLOSED
}
