package com.fintech.sre.agent.runtime.verification;

public enum VerificationRequestIntegrationReason {
	VERIFICATION_REQUESTABLE,
	PARTIAL_VERIFICATION_REQUEST,
	NOT_READY_VERIFICATION_REQUEST,
	UNRELIABLE_VERIFICATION_REQUEST,
	BLOCKED_VERIFICATION_REQUEST,
	MISSING_VERIFICATION_REQUEST_IDENTIFIER,
	MISSING_VERIFICATION_POLICY,
	MISSING_VERIFICATION_EVIDENCE_REQUIREMENT,
	MISSING_ROLLBACK_BINDING,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
