package com.fintech.sre.agent.runtime.verification;

public enum VerificationRequestReason {
	APPROVAL_DECISION_PENDING_VIEW,
	PARTIAL_APPROVAL_DECISION,
	NOT_READY_APPROVAL_DECISION,
	UNRELIABLE_APPROVAL_DECISION,
	BLOCKED_APPROVAL_DECISION,
	MISSING_VERIFICATION_REQUEST_IDENTIFIER,
	MISSING_VERIFICATION_POLICY,
	MISSING_VERIFICATION_EVIDENCE_REQUIREMENT,
	MISSING_ROLLBACK_BINDING,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
