package com.fintech.sre.agent.runtime.recommendation;

public enum RecommendationGenerationReason {
	CONTENT_READY,
	PARTIAL_CONTENT,
	NOT_READY_CONTENT,
	UNRELIABLE_CONTENT,
	BLOCKED_CONTENT,
	MISSING_SCENARIO_ID,
	MISSING_RUNBOOK_ID,
	MISSING_ROLLBACK_ID,
	MISSING_VERIFICATION_ID,
	MISSING_PAYMENT_SAFETY_CLASSIFICATION,
	INVALID_PAYMENT_SAFETY_CLASSIFICATION,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
