package com.fintech.sre.agent.runtime.recommendation;

public enum RecommendationContentIntegrationReason {
	VALID_CONTENT,
	PARTIAL_CONTENT,
	MISSING_SCENARIO_BINDING,
	MISSING_RUNBOOK_BINDING,
	MISSING_ROLLBACK_BINDING,
	MISSING_VERIFICATION_BINDING,
	MISSING_PAYMENT_SAFETY_CLASSIFICATION,
	INVALID_PAYMENT_SAFETY_CLASSIFICATION,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	RAW_PAYLOAD_PROTECTED,
	VENDOR_DETAIL_PROTECTED,
	CREDENTIAL_PROTECTED,
	CONFIGURATION_SECRET_PROTECTED,
	UNKNOWN
}
