package com.fintech.sre.agent.runtime.recommendation;

public enum RecommendationCandidateReason {
	ELIGIBLE_ACTION_ADMISSION,
	PARTIAL_ACTION_ADMISSION,
	NOT_READY_ACTION_ADMISSION,
	UNRELIABLE_ACTION_ADMISSION,
	BLOCKED_ACTION_ADMISSION,
	MISSING_SCENARIO_BINDING,
	MISSING_RUNBOOK_BINDING,
	MISSING_ROLLBACK_BINDING,
	MISSING_VERIFICATION_BINDING,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
