package com.fintech.sre.agent.runtime.recommendation;

public enum RecommendationCandidateIntegrationReason {
	ELIGIBLE_CANDIDATE,
	PARTIAL_CANDIDATE,
	NOT_READY_CANDIDATE,
	UNRELIABLE_CANDIDATE,
	BLOCKED_CANDIDATE,
	MISSING_SCENARIO_BINDING,
	MISSING_RUNBOOK_BINDING,
	MISSING_ROLLBACK_BINDING,
	MISSING_VERIFICATION_BINDING,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
