package com.fintech.sre.agent.runtime.recommendation;

public enum RecommendationModelIntegrationReason {
	VALID_RECOMMENDATION_MODEL,
	PARTIAL_RECOMMENDATION_MODEL,
	MISSING_SCENARIO_REFERENCE,
	MISSING_RUNBOOK_REFERENCE,
	MISSING_ROLLBACK_REFERENCE,
	MISSING_VERIFICATION_REFERENCE,
	MISSING_EVIDENCE_REFERENCE,
	MISSING_PAYMENT_SAFETY_CLASSIFICATION,
	INVALID_PAYMENT_SAFETY_CLASSIFICATION,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	RAW_PAYLOAD_PROTECTED,
	VENDOR_DETAIL_PROTECTED,
	CREDENTIAL_PROTECTED,
	CONFIGURATION_SECRET_PROTECTED,
	UNKNOWN
}
