package com.fintech.sre.agent.action;

public enum ActionType {
	SCALE_OUT,
	SCALE_DOWN,
	RATE_LIMIT,
	TRAFFIC_SHED,
	TRAFFIC_SHIFT,
	CIRCUIT_BREAKER_OPEN,
	CIRCUIT_BREAKER_CLOSE,
	RETRY_ADJUST,
	TIMEOUT_ADJUST,
	FALLBACK_ENABLE,
	FALLBACK_DISABLE,
	CACHE_BYPASS,
	CONNECTION_POOL_ADJUST,
	PAUSE_ROLLOUT,
	RESTART_POD,
	FAILOVER,
	OBSERVE_ONLY
}
