{
  "formatVersion": "1.1",
  "component": {
    "group": "io.projectreactor",
    "module": "reactor-test",
    "version": "3.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.8.5"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-test-3.8.5.jar",
          "url": "reactor-test-3.8.5.jar",
          "size": 143717,
          "sha512": "fbe19f3704c4fb404ef0fcf3b7c6aa0cb0bc10b5577e89faa6f5d4a368f97248c88d5abd2230d21edf7e98a24570abe0d9571efd97a1746421c89f43d955c562",
          "sha256": "3913085fc813ee6ee02558c7827d0e93414207ccf2b3b5870f23be51f20fbe23",
          "sha1": "bd19c7be679cab09cc37ac865b2ab94bf1609ef7",
          "md5": "86ae50835fe1cac48bd93cb1cd64a3fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.8.5"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-test-3.8.5.jar",
          "url": "reactor-test-3.8.5.jar",
          "size": 143717,
          "sha512": "fbe19f3704c4fb404ef0fcf3b7c6aa0cb0bc10b5577e89faa6f5d4a368f97248c88d5abd2230d21edf7e98a24570abe0d9571efd97a1746421c89f43d955c562",
          "sha256": "3913085fc813ee6ee02558c7827d0e93414207ccf2b3b5870f23be51f20fbe23",
          "sha1": "bd19c7be679cab09cc37ac865b2ab94bf1609ef7",
          "md5": "86ae50835fe1cac48bd93cb1cd64a3fb"
        }
      ]
    }
  ]
}
