{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-reactor-netty",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-reactor-netty-4.0.6.jar",
          "url": "spring-boot-reactor-netty-4.0.6.jar",
          "size": 41836,
          "sha512": "a6711e34865a286b44558ba7d082c460b0d9fe91097bed6b509b059a3083b7314cec037f39af9a5e29ef938fa041038da3c0bd9d14e03e2a6af342ad780f3585",
          "sha256": "639afc77a0950a6b0ca773afa26cb3e2d06cbf05044bec8656331bac4049802c",
          "sha1": "33a44436fe45d3bb6f1e08d7534b67b46155f0ce",
          "md5": "d10fa472f114d7860101bd345a4b4385"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-netty",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-reactor-netty-4.0.6.jar",
          "url": "spring-boot-reactor-netty-4.0.6.jar",
          "size": 41836,
          "sha512": "a6711e34865a286b44558ba7d082c460b0d9fe91097bed6b509b059a3083b7314cec037f39af9a5e29ef938fa041038da3c0bd9d14e03e2a6af342ad780f3585",
          "sha256": "639afc77a0950a6b0ca773afa26cb3e2d06cbf05044bec8656331bac4049802c",
          "sha1": "33a44436fe45d3bb6f1e08d7534b67b46155f0ce",
          "md5": "d10fa472f114d7860101bd345a4b4385"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-reactor-netty-4.0.6-javadoc.jar",
          "url": "spring-boot-reactor-netty-4.0.6-javadoc.jar",
          "size": 152803,
          "sha512": "12ff0ed8613d22d28d7543b8e038332fa919f2262fcc22e894779529a3a2182a468c8edd438c08a4c3122e18a1e06140dd908ecfa8e76233de51cf981dd6efce",
          "sha256": "b5e8cb4aa309a78df24fed1e50f60e2e8b80c99c9adf3f032f96321bfdb77471",
          "sha1": "09562f0db97911b4019f8dd6ee436f8d6bc22f46",
          "md5": "b82f6b72ff10456431d64fc29cfdc7d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-reactor-netty-4.0.6-sources.jar",
          "url": "spring-boot-reactor-netty-4.0.6-sources.jar",
          "size": 30288,
          "sha512": "2454046d4ae7a8d2f54ffaa49993d6160584576b7b64a974a50733048448d7eb63fea4baa1e7c3b777673ac9be39ca8f897213287b763bd8ef69b796b69f51a9",
          "sha256": "47c13481779cc37b45599b30ee69c682e0988b3517cd6b2dcbcee6d565b13579",
          "sha1": "7f1c9018d3e625f8a1e5db5cf7b9d2304743eafa",
          "md5": "42b6d6318871ff6b2d6778f32e87a562"
        }
      ]
    }
  ]
}
