package com.fintech.sre.agent.runtime.reliability;

public enum ActionAdmissionRejectionReason {
	SAFETY_POLICY_REJECTED,
	ACTION_COMMAND_BOUNDARY_REJECTED,
	RECOMMENDATION_BOUNDARY_REJECTED,
	SCENARIO_BINDING_REJECTED,
	ROLLBACK_VERIFICATION_BINDING_REJECTED,
	RESTRICTED_STATE_DISALLOWS_UNRESTRICTED_ADMISSION
}
