package com.fintech.sre.agent.runtime.reliability;

public enum ActionAdmissionReliabilityIntegrationReason {
	BLOCKED_ACTION_ADMISSION_RELIABILITY,
	UNRELIABLE_ACTION_ADMISSION_RELIABILITY,
	LOW_ACTION_ADMISSION_RELIABILITY,
	MEDIUM_ACTION_ADMISSION_RELIABILITY,
	HIGH_ACTION_ADMISSION_RELIABILITY,
	MISSING_ACTION_TYPE,
	MISSING_BLAST_RADIUS_BOUNDARY,
	MISSING_ROLLBACK_BINDING,
	MISSING_VERIFICATION_BINDING,
	MISSING_HUMAN_APPROVAL_REQUIREMENT,
	PAYMENT_SAFETY_UNCERTAINTY,
	CONTRADICTORY_ACTION_ADMISSION,
	UNKNOWN
}
