package com.fintech.sre.agent.runtime.reliability;

public enum ActionAdmissionReliabilityReason {
	HIGH_VERIFICATION_RELIABILITY,
	LOW_VERIFICATION_RELIABILITY,
	UNRELIABLE_VERIFICATION,
	BLOCKED_VERIFICATION,
	MISSING_ACTION_TYPE,
	MISSING_BLAST_RADIUS_BOUNDARY,
	MISSING_ROLLBACK_BINDING,
	MISSING_VERIFICATION_BINDING,
	MISSING_HUMAN_APPROVAL_REQUIREMENT,
	PAYMENT_SAFETY_UNCERTAINTY,
	CONTRADICTORY_VERIFICATION,
	UNKNOWN
}
