package com.fintech.sre.agent.runtime.reliability;

public enum ActionAdmissionReliabilityIntegrationScope {
	ACTION_ADMISSION_READY_VIEW,
	PARTIAL_ADMISSION_VIEW,
	OPERATOR_WARNING_VIEW,
	ACTION_ADMISSION_UNCERTAINTY,
	ACTION_COMMAND_CANDIDATE_FORBIDDEN,
	ACTION_TYPE_UNCERTAINTY,
	BLAST_RADIUS_UNCERTAINTY,
	ROLLBACK_UNCERTAINTY,
	VERIFICATION_BINDING_UNCERTAINTY,
	HUMAN_APPROVAL_UNCERTAINTY,
	PAYMENT_CRITICAL_RISK_VIEW,
	LIFECYCLE_UNCERTAINTY,
	UNKNOWN
}
