package com.fintech.sre.agent.runtime.reliability;

public enum ApprovalReliabilityReason {
	HIGH_RECOMMENDATION_RELIABILITY,
	LOW_RECOMMENDATION_RELIABILITY,
	UNRELIABLE_RECOMMENDATION,
	BLOCKED_RECOMMENDATION,
	MISSING_HUMAN_APPROVAL_REQUIREMENT,
	MISSING_OPERATOR_CONTEXT,
	MISSING_ROLLBACK_BINDING,
	MISSING_VERIFICATION_BINDING,
	PAYMENT_SAFETY_UNCERTAINTY,
	CONTRADICTORY_RECOMMENDATION,
	UNKNOWN
}
