package com.fintech.sre.agent.runtime.reliability;

public enum ApprovalReliabilityIntegrationScope {
	APPROVAL_READY_VIEW,
	PARTIAL_APPROVAL_VIEW,
	OPERATOR_WARNING_VIEW,
	APPROVAL_UNCERTAINTY,
	APPROVAL_FORBIDDEN,
	OPERATOR_CONTEXT_UNCERTAINTY,
	HUMAN_APPROVAL_UNCERTAINTY,
	ROLLBACK_UNCERTAINTY,
	VERIFICATION_UNCERTAINTY,
	PAYMENT_CRITICAL_RISK_VIEW,
	LIFECYCLE_UNCERTAINTY,
	UNKNOWN
}
