package com.fintech.sre.agent.runtime.reliability;

public enum ApprovalReliabilityIntegrationReason {
	BLOCKED_APPROVAL_RELIABILITY,
	UNRELIABLE_APPROVAL_RELIABILITY,
	LOW_APPROVAL_RELIABILITY,
	MEDIUM_APPROVAL_RELIABILITY,
	HIGH_APPROVAL_RELIABILITY,
	MISSING_OPERATOR_CONTEXT,
	MISSING_HUMAN_APPROVAL_REQUIREMENT,
	MISSING_ROLLBACK_BINDING,
	MISSING_VERIFICATION_BINDING,
	PAYMENT_SAFETY_UNCERTAINTY,
	CONTRADICTORY_APPROVAL,
	UNKNOWN
}
