package com.fintech.sre.agent.runtime.reliability;

public enum AssessmentLifecyclePipelineStage {
	RISK_CLASSIFICATION,
	HUMAN_APPROVAL_POLICY,
	RECOMMENDATION_BOUNDARY,
	ACTION_COMMAND_BOUNDARY,
	SCENARIO_BINDING,
	ROLLBACK_VERIFICATION_BINDING,
	SAFETY_POLICY_GATE,
	ACTION_ADMISSION,
	EXECUTION_READINESS,
	LIFECYCLE_SUMMARY
}
