package com.fintech.sre.agent.runtime.reliability;

public enum AssessmentReliabilityIntegrationReason {
	BLOCKED_ASSESSMENT_RELIABILITY,
	UNRELIABLE_ASSESSMENT_RELIABILITY,
	LOW_ASSESSMENT_RELIABILITY,
	MEDIUM_ASSESSMENT_RELIABILITY,
	HIGH_ASSESSMENT_RELIABILITY,
	PAYMENT_SAFETY_UNCERTAINTY,
	CONTRADICTORY_ASSESSMENT,
	UNKNOWN
}
