package com.fintech.sre.agent.runtime.reliability;

public enum AssessmentReliabilityReason {
	HIGH_EVIDENCE_RELIABILITY,
	LOW_EVIDENCE_RELIABILITY,
	UNRELIABLE_EVIDENCE,
	BLOCKED_EVIDENCE,
	INSUFFICIENT_CONFIDENCE,
	PAYMENT_SAFETY_UNCERTAINTY,
	CONTRADICTORY_EVIDENCE,
	UNKNOWN
}
