package com.fintech.sre.agent.runtime.reliability;

public enum ConvergenceRejectionReason {
	VERIFICATION_NOT_ADMITTED,
	VERIFICATION_ONLY_NOT_SUFFICIENT,
	PROPAGATION_STILL_ACTIVE,
	STABILIZATION_WINDOW_NOT_SATISFIED,
	CONTRADICTORY_EVIDENCE,
	TEMPORAL_STABILITY_NOT_SATISFIED
}
