package com.fintech.sre.agent.runtime.reliability;

public enum DecisionReliabilityIntegrationReason {
	BLOCKED_DECISION_RELIABILITY,
	UNRELIABLE_DECISION_RELIABILITY,
	LOW_DECISION_RELIABILITY,
	MEDIUM_DECISION_RELIABILITY,
	HIGH_DECISION_RELIABILITY,
	MISSING_SCENARIO_BINDING,
	MISSING_ROLLBACK_BINDING,
	MISSING_VERIFICATION_BINDING,
	PAYMENT_SAFETY_UNCERTAINTY,
	CONTRADICTORY_DECISION,
	UNKNOWN
}
