package com.fintech.sre.agent.runtime.reliability;

public enum DecisionReliabilityReason {
	HIGH_ASSESSMENT_RELIABILITY,
	LOW_ASSESSMENT_RELIABILITY,
	UNRELIABLE_ASSESSMENT,
	BLOCKED_ASSESSMENT,
	MISSING_SCENARIO_BINDING,
	MISSING_ROLLBACK_BINDING,
	MISSING_VERIFICATION_BINDING,
	PAYMENT_SAFETY_UNCERTAINTY,
	CONTRADICTORY_ASSESSMENT,
	UNKNOWN
}
