package com.fintech.sre.agent.runtime.reliability;

public enum DecisionReliabilityIntegrationScope {
	RELIABLE_DECISION_VIEW,
	PARTIAL_DECISION_VIEW,
	OPERATOR_WARNING_VIEW,
	RECOMMENDATION_UNCERTAINTY,
	LIFECYCLE_BLOCKED,
	SCENARIO_UNCERTAINTY,
	ROLLBACK_UNCERTAINTY,
	VERIFICATION_UNCERTAINTY,
	PAYMENT_RISK_VIEW,
	LIFECYCLE_UNCERTAINTY,
	UNKNOWN
}
