package com.fintech.sre.agent.runtime.reliability;

public enum EvidenceReliabilityReason {
	GOVERNANCE_BLOCKED,
	GOVERNANCE_RESTRICTED,
	INCOMPLETE_LINEAGE,
	UNTRUSTED_EVIDENCE,
	LOW_TRUST,
	INSUFFICIENT_CONFIDENCE,
	LOW_CONFIDENCE,
	CONTRADICTORY_EVIDENCE,
	PAYMENT_SAFETY_UNCERTAINTY,
	HIGH_RELIABILITY_EVIDENCE,
	UNKNOWN
}
