package com.fintech.sre.agent.runtime.reliability;

public enum EvidenceLineageReason {
	MISSING_PROVENANCE,
	GOVERNANCE_PROTECTED_EVIDENCE,
	BLOCKED_EVIDENCE,
	CONTRADICTORY_EVIDENCE,
	PAYMENT_RESTRICTED_EVIDENCE,
	MISSING_COLLECTION_STAGE,
	MISSING_ASSESSMENT_STAGE,
	UNKNOWN
}
