package com.fintech.sre.agent.runtime.reliability;

public enum EvidenceGovernanceIntegrationReason {
	UNTRUSTED_EVIDENCE,
	BLOCKED_CLASSIFICATION,
	GOVERNANCE_PROTECTED_CLASSIFICATION,
	CONTRADICTORY_INTEGRITY,
	PAYMENT_RESTRICTED_CLASSIFICATION,
	MISSING_PROVENANCE,
	UNSANITIZED_EVIDENCE,
	UNKNOWN
}
