package com.fintech.sre.agent.runtime.reliability;

public enum EvidenceTrustScoreReason {
	TRUSTED_PROVENANCE,
	PARTIAL_PROVENANCE,
	MISSING_PROVENANCE,
	COMPLETE_LINEAGE,
	INCOMPLETE_LINEAGE,
	INTACT_INTEGRITY,
	DEGRADED_INTEGRITY,
	CONTRADICTORY_EVIDENCE,
	BLOCKED_EVIDENCE,
	PAYMENT_RESTRICTED_EVIDENCE,
	UNKNOWN
}
