package com.fintech.sre.agent.runtime.reliability;

public enum EvidenceConfidenceReason {
	SUFFICIENT_EVIDENCE,
	PARTIAL_EVIDENCE,
	INSUFFICIENT_EVIDENCE,
	CORROBORATING_EVIDENCE,
	CONTRADICTORY_EVIDENCE,
	PAYMENT_EVIDENCE_MISSING,
	UNKNOWN_EVIDENCE,
	UNKNOWN
}
