package com.fintech.sre.agent.runtime.reliability;

public enum ExecutionBoundaryRejectionReason {
	ACTION_ADMISSION_NOT_ACCEPTED,
	EXPLICIT_EXECUTION_AUTHORIZATION_MISSING,
	APPROVAL_NOT_COMPLETED,
	ROLLBACK_REVIEW_NOT_COMPLETED,
	VERIFICATION_REVIEW_NOT_COMPLETED,
	PAYMENT_SAFETY_UNCERTAINTY,
	CONTRADICTORY_EVIDENCE,
	CRITICAL_EXECUTION_REQUIREMENTS_NOT_SATISFIED
}
