package com.fintech.sre.agent.runtime.reliability;

public enum ExecutionReadinessRejectionReason {
	EXECUTION_BOUNDARY_REJECTED,
	EXECUTION_PLAN_REJECTED,
	AUDIT_INTEGRITY_INCOMPLETE,
	MISSING_PAYMENT_CONSISTENCY_VERIFICATION,
	AI_ONLY_DECISION_NOT_ACCEPTABLE,
	CRITICAL_REQUIREMENTS_NOT_SATISFIED
}
