package com.fintech.sre.agent.runtime.reliability;

public enum ExecutionPlanRejectionReason {
	EXECUTION_NOT_ELIGIBLE,
	MISSING_ROLLBACK_PLAN_REFERENCE,
	MISSING_VERIFICATION_PLAN_REFERENCE,
	MISSING_PAYMENT_CONSISTENCY_VERIFICATION,
	AI_ONLY_APPROVAL_PROHIBITED,
	MISSING_EXPLICIT_EXECUTION_AUTHORIZATION
}
