package com.fintech.sre.agent.runtime.reliability;

public enum LifecycleAuditEventType {
	ASSESSMENT_RECORDED,
	ADMISSION_RECORDED,
	READINESS_RECORDED,
	EXECUTOR_RESPONSE_RECORDED,
	POST_VERIFICATION_RECORDED,
	POST_CONVERGENCE_RECORDED,
	POST_REGRESSION_RECORDED,
	AI_ONLY_DECISION_RECORDED
}
