package com.fintech.sre.agent.runtime.reliability;

public enum PostExecutionConvergenceRejectionReason {
	UNKNOWN_EXECUTOR_RESPONSE,
	VERIFICATION_NOT_SUFFICIENT,
	STABILIZATION_WINDOW_NOT_SATISFIED,
	PROPAGATION_STILL_ACTIVE,
	MISSING_PAYMENT_CONSISTENCY_VERIFICATION,
	CONTRADICTORY_POST_EXECUTION_EVIDENCE,
	ROLLBACK_VERIFICATION_REQUIRED
}
