package com.fintech.sre.agent.runtime.reliability;

public enum PostExecutionVerificationRejectionReason {
	EXECUTOR_RESPONSE_UNKNOWN,
	EXECUTION_ACKNOWLEDGEMENT_ONLY,
	MISSING_VERIFICATION_EVIDENCE,
	MISSING_PAYMENT_CONSISTENCY_VERIFICATION,
	CONTRADICTORY_POST_EXECUTION_EVIDENCE,
	ROLLBACK_VERIFICATION_REQUIRED,
	INCOMPLETE_VERIFICATION_EVIDENCE
}
