package com.fintech.sre.agent.runtime.reliability;

public enum RecommendationRestriction {
	NO_RECOMMENDATION_AVAILABLE,
	EXECUTION_AUTHORITY_PROHIBITED,
	UNSAFE_RECOMMENDATION_PROHIBITED,
	AUTOMATED_RECOMMENDATION_RESTRICTED,
	HUMAN_APPROVAL_REQUIRED,
	FAILED_STATE_RESTRICTED,
	CRITICAL_RISK_RESTRICTED
}
