package com.fintech.sre.agent.runtime.reliability;

public enum RecommendationReliabilityIntegrationScope {
	RELIABLE_RECOMMENDATION_VIEW,
	PARTIAL_RECOMMENDATION_VIEW,
	OPERATOR_WARNING_VIEW,
	RECOMMENDATION_UNCERTAINTY,
	RECOMMENDATION_FORBIDDEN,
	HUMAN_APPROVAL_UNCERTAINTY,
	ROLLBACK_UNCERTAINTY,
	VERIFICATION_UNCERTAINTY,
	PAYMENT_CRITICAL_RISK_VIEW,
	LIFECYCLE_UNCERTAINTY,
	UNKNOWN
}
