package com.fintech.sre.agent.runtime.reliability;

public enum RecommendationReliabilityReason {
	HIGH_DECISION_RELIABILITY,
	LOW_DECISION_RELIABILITY,
	UNRELIABLE_DECISION,
	BLOCKED_DECISION,
	MISSING_HUMAN_APPROVAL_REQUIREMENT,
	MISSING_ROLLBACK_BINDING,
	MISSING_VERIFICATION_BINDING,
	PAYMENT_SAFETY_UNCERTAINTY,
	CONTRADICTORY_DECISION,
	UNKNOWN
}
