package com.fintech.sre.agent.runtime.reliability;

public enum RecommendationReliabilityIntegrationReason {
	BLOCKED_RECOMMENDATION_RELIABILITY,
	UNRELIABLE_RECOMMENDATION_RELIABILITY,
	LOW_RECOMMENDATION_RELIABILITY,
	MEDIUM_RECOMMENDATION_RELIABILITY,
	HIGH_RECOMMENDATION_RELIABILITY,
	MISSING_HUMAN_APPROVAL_REQUIREMENT,
	MISSING_ROLLBACK_BINDING,
	MISSING_VERIFICATION_BINDING,
	PAYMENT_SAFETY_UNCERTAINTY,
	CONTRADICTORY_RECOMMENDATION,
	UNKNOWN
}
