package com.fintech.sre.agent.runtime.reliability;

public enum ReliabilityLifecycleStage {
	PRE_EXECUTION_ASSESSMENT,
	ACTION_ADMISSION,
	EXECUTION_READINESS,
	EXECUTOR_RESPONSE,
	POST_EXECUTION_VERIFICATION,
	POST_EXECUTION_CONVERGENCE,
	POST_EXECUTION_REGRESSION
}
