package com.fintech.sre.agent.runtime.reliability;

public enum ReliabilityLifecycleSummaryReason {
	STABLE_CONVERGENCE_CONFIRMED,
	AUDIT_INTEGRITY_INCOMPLETE,
	PAYMENT_INCONSISTENCY_DETECTED,
	REGRESSION_DETECTED,
	EXECUTION_ACKNOWLEDGEMENT_ONLY,
	POST_EXECUTION_VERIFICATION_CONFIRMED,
	EXECUTOR_RESPONSE_FAILED,
	EXECUTOR_RESPONSE_UNKNOWN
}
