package com.fintech.sre.agent.runtime.reliability;

public enum ReliabilityLifecycleRejectionReason {
	PRE_EXECUTION_ASSESSMENT_REJECTED,
	ACTION_ADMISSION_REJECTED,
	EXECUTION_READINESS_REJECTED,
	EXECUTOR_RESPONSE_FAILED,
	EXECUTOR_RESPONSE_UNKNOWN,
	POST_EXECUTION_VERIFICATION_REQUIRED,
	CONVERGENCE_REQUIRES_POST_EXECUTION_VERIFICATION,
	POST_EXECUTION_CONVERGENCE_REQUIRED,
	POST_EXECUTION_REGRESSION_DETECTED
}
