package com.fintech.sre.agent.runtime.reliability;

public enum ReliabilityRiskFactor {
	FAILED_STATE,
	PAYMENT_SAFETY_UNCERTAINTY,
	CONTRADICTORY_EVIDENCE,
	ACTIVE_PROPAGATION_WITH_PARTIAL_EVIDENCE,
	PARTIAL_EVIDENCE,
	ABSENT_EVIDENCE,
	UNKNOWN_RUNTIME_STATE,
	POST_CONVERGENCE_REGRESSION,
	STABLE_CONVERGED_COMPLETE_EVIDENCE
}
