package com.fintech.sre.agent.runtime.reliability;

public enum RuntimeTransitionRejectionReason {
	GENERIC_TRANSITION_NOT_ALLOWED,
	UNKNOWN_CANNOT_CONVERGE_DIRECTLY,
	PROPAGATING_REQUIRES_VERIFICATION,
	ROLLBACK_REQUIRES_VERIFIED_OR_FAILED,
	CONVERGENCE_REQUIRES_VERIFIED_STATE,
	FAILED_IS_TERMINAL,
	PAYMENT_SAFETY_UNCERTAINTY,
	ROLLBACK_UNAVAILABLE
}
