package com.fintech.sre.agent.runtime.reliability;

public enum SafetyPolicyRejectionReason {
	NO_SCENARIO,
	MISSING_ROLLBACK_BINDING,
	MISSING_VERIFICATION_BINDING,
	UNKNOWN_ROLLBACK_BINDING,
	UNKNOWN_VERIFICATION_BINDING,
	PAYMENT_SAFETY_UNCERTAINTY,
	CONTRADICTORY_EVIDENCE,
	HIGH_RISK_APPROVAL_MISSING,
	CRITICAL_EXPLICIT_APPROVAL_MISSING,
	MISSING_PAYMENT_CONSISTENCY_VERIFICATION
}
