package com.fintech.sre.agent.runtime.reliability;

public enum VerificationReliabilityIntegrationScope {
	VERIFICATION_READY_VIEW,
	PARTIAL_VERIFICATION_VIEW,
	OPERATOR_WARNING_VIEW,
	VERIFICATION_UNCERTAINTY,
	VERIFICATION_FORBIDDEN,
	VERIFICATION_BINDING_UNCERTAINTY,
	VERIFICATION_EVIDENCE_UNCERTAINTY,
	ROLLBACK_UNCERTAINTY,
	PAYMENT_CRITICAL_RISK_VIEW,
	LIFECYCLE_UNCERTAINTY,
	UNKNOWN
}
