package com.fintech.sre.agent.runtime.reliability;

public enum VerificationReliabilityIntegrationReason {
	BLOCKED_VERIFICATION_RELIABILITY,
	UNRELIABLE_VERIFICATION_RELIABILITY,
	LOW_VERIFICATION_RELIABILITY,
	MEDIUM_VERIFICATION_RELIABILITY,
	HIGH_VERIFICATION_RELIABILITY,
	MISSING_VERIFICATION_BINDING,
	MISSING_VERIFICATION_EVIDENCE_REQUIREMENT,
	MISSING_ROLLBACK_BINDING,
	PAYMENT_SAFETY_UNCERTAINTY,
	CONTRADICTORY_VERIFICATION,
	UNKNOWN
}
