package com.fintech.sre.agent.runtime.reliability;

public enum VerificationReliabilityReason {
	HIGH_APPROVAL_RELIABILITY,
	LOW_APPROVAL_RELIABILITY,
	UNRELIABLE_APPROVAL,
	BLOCKED_APPROVAL,
	MISSING_VERIFICATION_BINDING,
	MISSING_VERIFICATION_EVIDENCE_REQUIREMENT,
	MISSING_ROLLBACK_BINDING,
	PAYMENT_SAFETY_UNCERTAINTY,
	CONTRADICTORY_APPROVAL,
	CONTRADICTORY_RECOMMENDATION,
	UNKNOWN
}
