{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-webtestclient",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-http-codec",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-webtestclient-4.0.6.jar",
          "url": "spring-boot-webtestclient-4.0.6.jar",
          "size": 12107,
          "sha512": "db8ee132fe0762d29202ae567898dd1b041eeaf25ab32b58b1456c7ab870bdd79b021ce1c52403ebc3a2c805fb6be24b863d5d3c1f48d61e0d9a4569e956b511",
          "sha256": "ffa468cbfbea986b42c2c06ca0b6a30874d5994668c4fee76f039a32ebf71039",
          "sha1": "d34a55af97353917dea444920f52cf0727b2ac0f",
          "md5": "d467d5c0d4714cf7d997d63d40a2f3fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-http-codec",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-webtestclient-4.0.6.jar",
          "url": "spring-boot-webtestclient-4.0.6.jar",
          "size": 12107,
          "sha512": "db8ee132fe0762d29202ae567898dd1b041eeaf25ab32b58b1456c7ab870bdd79b021ce1c52403ebc3a2c805fb6be24b863d5d3c1f48d61e0d9a4569e956b511",
          "sha256": "ffa468cbfbea986b42c2c06ca0b6a30874d5994668c4fee76f039a32ebf71039",
          "sha1": "d34a55af97353917dea444920f52cf0727b2ac0f",
          "md5": "d467d5c0d4714cf7d997d63d40a2f3fd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-webtestclient-4.0.6-javadoc.jar",
          "url": "spring-boot-webtestclient-4.0.6-javadoc.jar",
          "size": 116572,
          "sha512": "4ed3e8f1cbce803828add25413ff373a881147a020a2705a47de6abf0b7f0283fe9d27fee029632cd003b0aa43e003ebdae1be1bcd628ea4a549d8d7a34da796",
          "sha256": "385d0b94b8f493a5641cf465442b875a8b85749a13d2d2cfeffb3a3c7edc1618",
          "sha1": "6d569d1af97dcdb97d79ae9311a0332e18c7ef54",
          "md5": "80892327461c030684c4fc04a308d458"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-webtestclient-4.0.6-sources.jar",
          "url": "spring-boot-webtestclient-4.0.6-sources.jar",
          "size": 11615,
          "sha512": "a2fa2b7a190296097c83a2c3cbe4ef1280cbadece565317dd829512f80ae4e4a158a392cf85b3ab801e077affb120ee89502d8ea44090233b280103a0bd4dfcd",
          "sha256": "503b9a72d481248abc905dd54869b74503ab8557c48e7b7579e3565e09e57a27",
          "sha1": "9430025e7c8e51f7f8b54f8036d3a06bec725588",
          "md5": "b15118023199832be1d58d1db681cbce"
        }
      ]
    }
  ]
}
