package com.fintech.sre.agent.runtime.action;

public enum ActionCommandReason {
	VERIFICATION_REQUEST_READY,
	PARTIAL_VERIFICATION_REQUEST,
	NOT_READY_VERIFICATION_REQUEST,
	UNRELIABLE_VERIFICATION_REQUEST,
	BLOCKED_VERIFICATION_REQUEST,
	MISSING_ACTION_COMMAND_IDENTIFIER,
	MISSING_ACTION_TYPE,
	MISSING_TARGET_LAYER,
	MISSING_BLAST_RADIUS_BOUNDARY,
	MISSING_ROLLBACK_BINDING,
	MISSING_VERIFICATION_BINDING,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
