package com.fintech.sre.agent.runtime.action;

public enum ActionCommandIntegrationReason {
	ACTION_COMMAND_READY,
	PARTIAL_ACTION_COMMAND,
	NOT_READY_ACTION_COMMAND,
	UNRELIABLE_ACTION_COMMAND,
	BLOCKED_ACTION_COMMAND,
	MISSING_ACTION_COMMAND_IDENTIFIER,
	MISSING_ACTION_TYPE,
	MISSING_TARGET_LAYER,
	MISSING_BLAST_RADIUS_BOUNDARY,
	MISSING_ROLLBACK_BINDING,
	MISSING_VERIFICATION_BINDING,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
