{
  "formatVersion": "1.1",
  "component": {
    "group": "io.projectreactor",
    "module": "reactor-core",
    "version": "3.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-core-3.8.5.jar",
          "url": "reactor-core-3.8.5.jar",
          "size": 1938751,
          "sha512": "00ec8e0cf5559bbc72adb81ded97b69003f2ec81fdd951d684246c7676b0ea5e0930ad894a511ba3aa25da45dbe01a1fceeb4325ae2bebcfa350cb4d1313575d",
          "sha256": "c4a1cc8bce7f5e743ad6b34dcf2ca0b101f4b92d564fe7e006455324be625281",
          "sha1": "e3afac59d35d67364b64389e2ed7cd274829df71",
          "md5": "54224a7c87fa97cb28f7b714814ffe8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-core-3.8.5.jar",
          "url": "reactor-core-3.8.5.jar",
          "size": 1938751,
          "sha512": "00ec8e0cf5559bbc72adb81ded97b69003f2ec81fdd951d684246c7676b0ea5e0930ad894a511ba3aa25da45dbe01a1fceeb4325ae2bebcfa350cb4d1313575d",
          "sha256": "c4a1cc8bce7f5e743ad6b34dcf2ca0b101f4b92d564fe7e006455324be625281",
          "sha1": "e3afac59d35d67364b64389e2ed7cd274829df71",
          "md5": "54224a7c87fa97cb28f7b714814ffe8f"
        }
      ]
    }
  ]
}
