package com.fintech.sre.agent.runtime.approval;

public enum ApprovalDecisionReason {
	APPROVAL_PENDING_VIEW,
	PARTIAL_APPROVAL_STATE,
	NOT_READY_APPROVAL_STATE,
	UNRELIABLE_APPROVAL_STATE,
	BLOCKED_APPROVAL_STATE,
	MISSING_DECISION_IDENTIFIER,
	MISSING_APPROVAL_POLICY,
	MISSING_OPERATOR_CONTEXT,
	MISSING_DECISION_RATIONALE_REQUIREMENT,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
