package com.fintech.sre.agent.runtime.approval;

public enum ApprovalStateIntegrationReason {
	PENDING_APPROVAL_STATE,
	PARTIAL_APPROVAL_STATE,
	NOT_READY_APPROVAL_STATE,
	UNRELIABLE_APPROVAL_STATE,
	BLOCKED_APPROVAL_STATE,
	MISSING_APPROVAL_STATE_IDENTIFIER,
	MISSING_APPROVAL_POLICY,
	MISSING_OPERATOR_CONTEXT,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
