package com.fintech.sre.agent.runtime.approval;

public enum ApprovalDecisionIntegrationReason {
	DECISION_PENDING,
	PARTIAL_APPROVAL_DECISION,
	NOT_READY_APPROVAL_DECISION,
	UNRELIABLE_APPROVAL_DECISION,
	BLOCKED_APPROVAL_DECISION,
	MISSING_DECISION_IDENTIFIER,
	MISSING_APPROVAL_POLICY,
	MISSING_OPERATOR_CONTEXT,
	MISSING_DECISION_RATIONALE_REQUIREMENT,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
