package com.fintech.sre.agent.runtime.approval;

public enum ApprovalStateReason {
	APPROVAL_REQUEST_READY,
	PARTIAL_APPROVAL_REQUEST,
	NOT_READY_APPROVAL_REQUEST,
	UNRELIABLE_APPROVAL_REQUEST,
	BLOCKED_APPROVAL_REQUEST,
	MISSING_APPROVAL_STATE_IDENTIFIER,
	MISSING_APPROVAL_POLICY,
	MISSING_OPERATOR_CONTEXT,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
