package com.fintech.sre.agent.runtime.approval;

public enum ApprovalRequestIntegrationReason {
	REQUESTABLE_APPROVAL_REQUEST,
	PARTIAL_APPROVAL_REQUEST,
	NOT_READY_APPROVAL_REQUEST,
	UNRELIABLE_APPROVAL_REQUEST,
	BLOCKED_APPROVAL_REQUEST,
	MISSING_OPERATOR_CONTEXT,
	MISSING_HUMAN_APPROVAL_REQUIREMENT,
	MISSING_APPROVAL_POLICY,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
