package com.fintech.sre.agent.runtime.approval;

public enum ApprovalRequestReason {
	EXPOSABLE_PRESENTATION,
	PARTIAL_PRESENTATION,
	NOT_READY_PRESENTATION,
	UNRELIABLE_PRESENTATION,
	BLOCKED_PRESENTATION,
	MISSING_OPERATOR_CONTEXT,
	MISSING_HUMAN_APPROVAL_REQUIREMENT,
	MISSING_APPROVAL_POLICY,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
