{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-webflux-test",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webflux",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webtestclient",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-webflux-test-4.0.6.jar",
          "url": "spring-boot-webflux-test-4.0.6.jar",
          "size": 10833,
          "sha512": "230bf143d9f07104af4e78ece421843daab22ab54778d7dc41dded7cab608b73387246ed9ae3338c93033f5653ec4d23747f45ea182dcb34973bad6432acb2ef",
          "sha256": "2018a8560134f37f6726c69b63f04f413b7665c5b9b776b392cc11183fddf8a9",
          "sha1": "a4d845ecba7e86bc20978752fb21472e959170e2",
          "md5": "2c39290c5d5c800730e4155c304fdb43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webflux",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webtestclient",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-webflux-test-4.0.6.jar",
          "url": "spring-boot-webflux-test-4.0.6.jar",
          "size": 10833,
          "sha512": "230bf143d9f07104af4e78ece421843daab22ab54778d7dc41dded7cab608b73387246ed9ae3338c93033f5653ec4d23747f45ea182dcb34973bad6432acb2ef",
          "sha256": "2018a8560134f37f6726c69b63f04f413b7665c5b9b776b392cc11183fddf8a9",
          "sha1": "a4d845ecba7e86bc20978752fb21472e959170e2",
          "md5": "2c39290c5d5c800730e4155c304fdb43"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-webflux-test-4.0.6-javadoc.jar",
          "url": "spring-boot-webflux-test-4.0.6-javadoc.jar",
          "size": 110619,
          "sha512": "bdfde3f4e931818e0dfa335f5e89e9a47864ffc5f9c4fc1848f7ec11c7caca1094a5e469129aed06db0098a97b99254d33c232fbd77ca0badeed54cdd543a5ca",
          "sha256": "dcce511fd83b045dc1d9998c8ae7f41744b9f7f7c22f9f8eee491be18571da95",
          "sha1": "a49b719898367d75e8074563217cb60d1e3c14ca",
          "md5": "3447243e692d1955f35ed06bb921f82c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-webflux-test-4.0.6-sources.jar",
          "url": "spring-boot-webflux-test-4.0.6-sources.jar",
          "size": 12551,
          "sha512": "3f4b6cb93aaac76ca347aab340dbb0da91358c8bbc68eb28d8504b99b44ffe7a4e61f1572de287b18b426365c488dd1369225a77aafeccc15021399464d9c0d8",
          "sha256": "2b82d43942f4ee8e39101fd4bc688de41af26792cc6551f9e8b60e88c15f7be0",
          "sha1": "d0aa696d4247e36414dde73700facf4cc4fdce72",
          "md5": "06e577ce8b03c66643e48256994ccd35"
        }
      ]
    }
  ]
}
