package com.fintech.sre.agent.runtime.execution;

public enum ExecutionDispatchReason {
	EXECUTION_PLAN_READY,
	PARTIAL_EXECUTION_PLAN,
	NOT_READY_EXECUTION_PLAN,
	UNRELIABLE_EXECUTION_PLAN,
	BLOCKED_EXECUTION_PLAN,
	MISSING_DISPATCH_IDENTIFIER,
	MISSING_EXECUTION_ENDPOINT,
	MISSING_DISPATCH_POLICY,
	MISSING_DISPATCH_GUARDRAIL,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
