package com.fintech.sre.agent.runtime.execution;

public enum ExecutionEngineIntegrationReason {
	EXECUTION_ENGINE_READY,
	PARTIAL_EXECUTION_ENGINE,
	NOT_READY_EXECUTION_ENGINE,
	UNRELIABLE_EXECUTION_ENGINE,
	BLOCKED_EXECUTION_ENGINE,
	MISSING_EXECUTION_ENGINE_IDENTIFIER,
	MISSING_EXECUTION_ENGINE_TYPE,
	MISSING_EXECUTION_ENDPOINT_BINDING,
	MISSING_EXECUTION_POLICY,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
