package com.fintech.sre.agent.runtime.execution;

public enum ExecutionExecutorReason {
	EXECUTION_ADAPTER_READY,
	PARTIAL_EXECUTION_ADAPTER,
	NOT_READY_EXECUTION_ADAPTER,
	UNRELIABLE_EXECUTION_ADAPTER,
	BLOCKED_EXECUTION_ADAPTER,
	MISSING_EXECUTOR_IDENTIFIER,
	MISSING_EXECUTION_STRATEGY,
	MISSING_EXECUTION_BOUNDARY,
	MISSING_EXECUTOR_POLICY,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
