package com.fintech.sre.agent.runtime.execution;

public enum ExecutionExecutorIntegrationReason {
	EXECUTION_EXECUTOR_READY,
	PARTIAL_EXECUTION_EXECUTOR,
	NOT_READY_EXECUTION_EXECUTOR,
	UNRELIABLE_EXECUTION_EXECUTOR,
	BLOCKED_EXECUTION_EXECUTOR,
	MISSING_EXECUTOR_IDENTIFIER,
	MISSING_EXECUTION_STRATEGY,
	MISSING_EXECUTION_BOUNDARY,
	MISSING_EXECUTOR_POLICY,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
