package com.fintech.sre.agent.runtime.execution;

public enum ExecutionEngineSelectorReason {
	EXECUTION_ENGINE_REGISTRY_READY,
	PARTIAL_EXECUTION_ENGINE_REGISTRY,
	NOT_READY_EXECUTION_ENGINE_REGISTRY,
	UNRELIABLE_EXECUTION_ENGINE_REGISTRY,
	BLOCKED_EXECUTION_ENGINE_REGISTRY,
	MISSING_SELECTOR_IDENTIFIER,
	MISSING_ENGINE_SELECTION_POLICY,
	MISSING_ENGINE_CAPABILITY_REQUIREMENT,
	MISSING_SELECTOR_GUARDRAIL,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
