package com.fintech.sre.agent.runtime.execution;

public enum ExecutionContextIntegrationReason {
	EXECUTION_CONTEXT_READY,
	PARTIAL_EXECUTION_CONTEXT,
	NOT_READY_EXECUTION_CONTEXT,
	UNRELIABLE_EXECUTION_CONTEXT,
	BLOCKED_EXECUTION_CONTEXT,
	MISSING_CONTEXT_IDENTIFIER,
	MISSING_EXECUTION_CONTEXT_SCOPE,
	MISSING_EXECUTION_METADATA,
	MISSING_CONTEXT_POLICY,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
