package com.fintech.sre.agent.runtime.execution;

public enum ExecutionContextReason {
	EXECUTION_SESSION_READY,
	PARTIAL_EXECUTION_SESSION,
	NOT_READY_EXECUTION_SESSION,
	UNRELIABLE_EXECUTION_SESSION,
	BLOCKED_EXECUTION_SESSION,
	MISSING_CONTEXT_IDENTIFIER,
	MISSING_EXECUTION_CONTEXT_SCOPE,
	MISSING_EXECUTION_METADATA,
	MISSING_CONTEXT_POLICY,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
