package com.fintech.sre.agent.runtime.execution;

public enum ExecutionPlanIntegrationReason {
	EXECUTION_PLAN_READY,
	PARTIAL_EXECUTION_PLAN,
	NOT_READY_EXECUTION_PLAN,
	UNRELIABLE_EXECUTION_PLAN,
	BLOCKED_EXECUTION_PLAN,
	MISSING_EXECUTION_PLAN_IDENTIFIER,
	MISSING_EXECUTION_SEQUENCE,
	MISSING_ROLLBACK_PLAN,
	MISSING_VERIFICATION_PLAN,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
