package com.fintech.sre.agent.runtime.execution;

public enum ExecutionEngineReason {
	DISPATCH_READY,
	PARTIAL_DISPATCH,
	NOT_READY_DISPATCH,
	UNRELIABLE_DISPATCH,
	BLOCKED_DISPATCH,
	MISSING_EXECUTION_ENGINE_IDENTIFIER,
	MISSING_EXECUTION_ENGINE_TYPE,
	MISSING_EXECUTION_ENDPOINT_BINDING,
	MISSING_EXECUTION_POLICY,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
