package com.fintech.sre.agent.runtime.execution;

public enum ExecutionAdapterIntegrationReason {
	EXECUTION_ADAPTER_READY,
	PARTIAL_EXECUTION_ADAPTER,
	NOT_READY_EXECUTION_ADAPTER,
	UNRELIABLE_EXECUTION_ADAPTER,
	BLOCKED_EXECUTION_ADAPTER,
	MISSING_ADAPTER_IDENTIFIER,
	MISSING_ADAPTER_TYPE,
	MISSING_ADAPTER_BINDING,
	MISSING_ADAPTER_POLICY,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
