package com.fintech.sre.agent.runtime.execution;

public enum ExecutionSessionReason {
	EXECUTION_EXECUTOR_READY,
	PARTIAL_EXECUTION_EXECUTOR,
	NOT_READY_EXECUTION_EXECUTOR,
	UNRELIABLE_EXECUTION_EXECUTOR,
	BLOCKED_EXECUTION_EXECUTOR,
	MISSING_SESSION_IDENTIFIER,
	MISSING_EXECUTION_CORRELATION_IDENTIFIER,
	MISSING_EXECUTION_SCOPE,
	MISSING_SESSION_POLICY,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
