package com.fintech.sre.agent.runtime.execution;

public enum ExecutionPermissionReason {
	ACTION_COMMAND_CANDIDATE_READY,
	PARTIAL_ACTION_COMMAND,
	NOT_READY_ACTION_COMMAND,
	UNRELIABLE_ACTION_COMMAND,
	BLOCKED_ACTION_COMMAND,
	MISSING_EXECUTION_PERMISSION_IDENTIFIER,
	MISSING_EXECUTION_POLICY,
	MISSING_OPERATOR_AUTHORIZATION,
	MISSING_EXECUTION_GUARDRAIL,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
