package com.fintech.sre.agent.runtime.execution;

public enum ExecutionEngineRegistryReason {
	EXECUTION_ENGINE_READY,
	PARTIAL_EXECUTION_ENGINE,
	NOT_READY_EXECUTION_ENGINE,
	UNRELIABLE_EXECUTION_ENGINE,
	BLOCKED_EXECUTION_ENGINE,
	MISSING_REGISTRY_IDENTIFIER,
	MISSING_ENGINE_REGISTRATION,
	MISSING_REGISTRY_POLICY,
	MISSING_REGISTRY_GUARDRAIL,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
