package com.fintech.sre.agent.runtime.execution;

public enum ExecutionSessionIntegrationReason {
	EXECUTION_SESSION_READY,
	PARTIAL_EXECUTION_SESSION,
	NOT_READY_EXECUTION_SESSION,
	UNRELIABLE_EXECUTION_SESSION,
	BLOCKED_EXECUTION_SESSION,
	MISSING_SESSION_IDENTIFIER,
	MISSING_EXECUTION_CORRELATION_IDENTIFIER,
	MISSING_EXECUTION_SCOPE,
	MISSING_SESSION_POLICY,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
