package com.fintech.sre.agent.runtime.execution;

public enum ExecutionAdapterReason {
	EXECUTION_ENGINE_SELECTOR_READY,
	PARTIAL_EXECUTION_ENGINE_SELECTOR,
	NOT_READY_EXECUTION_ENGINE_SELECTOR,
	UNRELIABLE_EXECUTION_ENGINE_SELECTOR,
	BLOCKED_EXECUTION_ENGINE_SELECTOR,
	MISSING_ADAPTER_IDENTIFIER,
	MISSING_ADAPTER_TYPE,
	MISSING_ADAPTER_BINDING,
	MISSING_ADAPTER_POLICY,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
