package com.fintech.sre.agent.runtime.execution;

public enum ExecutionPermissionIntegrationReason {
	EXECUTION_PERMITTED,
	PARTIAL_EXECUTION_PERMISSION,
	NOT_READY_EXECUTION_PERMISSION,
	UNRELIABLE_EXECUTION_PERMISSION,
	BLOCKED_EXECUTION_PERMISSION,
	MISSING_EXECUTION_PERMISSION_IDENTIFIER,
	MISSING_EXECUTION_POLICY,
	MISSING_OPERATOR_AUTHORIZATION,
	MISSING_EXECUTION_GUARDRAIL,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
