package com.fintech.sre.agent.runtime.execution;

public enum ExecutionPlanReason {
	EXECUTION_PERMISSION_READY,
	PARTIAL_EXECUTION_PERMISSION,
	NOT_READY_EXECUTION_PERMISSION,
	UNRELIABLE_EXECUTION_PERMISSION,
	BLOCKED_EXECUTION_PERMISSION,
	MISSING_EXECUTION_PLAN_IDENTIFIER,
	MISSING_EXECUTION_SEQUENCE,
	MISSING_ROLLBACK_PLAN,
	MISSING_VERIFICATION_PLAN,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
