package com.fintech.sre.agent.runtime.execution;

public enum ExecutionDispatchIntegrationReason {
	DISPATCH_READY,
	PARTIAL_DISPATCH,
	NOT_READY_DISPATCH,
	UNRELIABLE_DISPATCH,
	BLOCKED_DISPATCH,
	MISSING_DISPATCH_IDENTIFIER,
	MISSING_EXECUTION_ENDPOINT,
	MISSING_DISPATCH_POLICY,
	MISSING_DISPATCH_GUARDRAIL,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	UNKNOWN
}
