{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-netty",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-netty-4.0.6.jar",
          "url": "spring-boot-netty-4.0.6.jar",
          "size": 9809,
          "sha512": "1ef89628d7d3ebdccf0273fd3d8169e7b019d6f12f90451cf67cc3c4f6f39724baee35bef3576badbbe475b3f2421d76691e004dc835b98818b78eb4e7bd93a8",
          "sha256": "cc32af938a1573b9c05bbe5ec46c5288af506f5abcd582cbd86b43fa374936e4",
          "sha1": "3b4262348951f383dbe48b57628b6ea12fa4d0d7",
          "md5": "e54899aaf0c5ab97b4727bad4d795ee8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-common",
          "version": {
            "requires": "4.2.12.Final"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-netty-4.0.6.jar",
          "url": "spring-boot-netty-4.0.6.jar",
          "size": 9809,
          "sha512": "1ef89628d7d3ebdccf0273fd3d8169e7b019d6f12f90451cf67cc3c4f6f39724baee35bef3576badbbe475b3f2421d76691e004dc835b98818b78eb4e7bd93a8",
          "sha256": "cc32af938a1573b9c05bbe5ec46c5288af506f5abcd582cbd86b43fa374936e4",
          "sha1": "3b4262348951f383dbe48b57628b6ea12fa4d0d7",
          "md5": "e54899aaf0c5ab97b4727bad4d795ee8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-netty-4.0.6-javadoc.jar",
          "url": "spring-boot-netty-4.0.6-javadoc.jar",
          "size": 113853,
          "sha512": "f9f65d1fe61ee0328eab06e2830c71ea27b49b02296ec1cf0fe59056757b56d7f7dbb121e521b2a7af60973c2532d7e341715188e1a94e7731bc9f8720827e8b",
          "sha256": "d2ababbe8be40b7f938d06240faee5ffd6086c31bc5613d5cf5a9553f71c64bd",
          "sha1": "86e40b5ff3d3ef9e1eb8cbb9692daca0aede0cb9",
          "md5": "9a1226aff135b3edc2ddf566f0493a87"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-netty-4.0.6-sources.jar",
          "url": "spring-boot-netty-4.0.6-sources.jar",
          "size": 8729,
          "sha512": "ad0bee1ac4eef64d762d8a8e78b0ed2339cadb3a10888f7563a9c36168959716af14253db8d17961d7f75fe575720a71ba60a10e62fc921e9df4583448e4a900",
          "sha256": "458ad22d22718f95b2e8a18cb4b91ccbbb2b63404a3bbd3fd07f96bc2c030b60",
          "sha1": "21618617cd2b7156dc9dd21a6999971844e0b344",
          "md5": "a037403e38e09169680ca3758069ff2b"
        }
      ]
    }
  ]
}
