package com.fintech.sre.agent.governance.timeline;

public enum GovernanceTimelineProjectionType {
	RECOMMENDATION_RECORD,
	APPROVAL_RECORD,
	EXECUTION_PLAN,
	HUMAN_EXECUTION_RESULT,
	VERIFICATION_RESULT,
	INCIDENT_LIFECYCLE,
	POSTMORTEM_DRAFT,
	POSTMORTEM_REVIEW,
	LEARNING_CANDIDATE,
	KNOWLEDGE_PROMOTION_REVIEW,
	KNOWLEDGE_PROMOTION_PLAN,
	KNOWLEDGE_UPDATE_APPLICATION
}
