package com.fintech.sre.agent.governance.timeline;

public enum GovernanceTimelineAggregationSource {
	RECOMMENDATION,
	APPROVAL,
	EXECUTION_PLAN,
	HUMAN_EXECUTION,
	VERIFICATION,
	INCIDENT_LIFECYCLE,
	POSTMORTEM_DRAFT,
	POSTMORTEM_REVIEW,
	LEARNING_CANDIDATE,
	KNOWLEDGE_PROMOTION_REVIEW,
	KNOWLEDGE_PROMOTION_PLAN,
	KNOWLEDGE_UPDATE
}
