package com.fintech.sre.agent.governance.timeline;

public enum GovernanceTimelineEventType {
	RECOMMENDATION_CREATED,
	APPROVAL_DECIDED,
	EXECUTION_PLAN_CREATED,
	HUMAN_EXECUTION_RECORDED,
	VERIFICATION_RECORDED,
	INCIDENT_TRANSITIONED,
	POSTMORTEM_DRAFT_CREATED,
	POSTMORTEM_REVIEWED,
	LEARNING_CANDIDATE_CREATED,
	PROMOTION_REVIEWED,
	PROMOTION_PLAN_CREATED,
	KNOWLEDGE_UPDATED
}
