package com.fintech.sre.agent.evidence;

public enum EvidenceSignal {
	P99_LATENCY_HIGH,
	ERROR_RATE_HIGH,
	TRAFFIC_SPIKE,
	DB_POOL_PENDING_HIGH,
	DB_LOCK_WAIT_HIGH,
	DB_CONNECTION_EXHAUSTED,
	KAFKA_CONSUMER_LAG_HIGH,
	KAFKA_REBALANCE_STORM,
	KAFKA_DLQ_RATE_HIGH,
	KAFKA_CONSUMER_RATE_LOW,
	REDIS_TIMEOUT_HIGH,
	REDIS_ERROR_RATE_HIGH,
	RETRY_RATE_HIGH,
	RETRY_STORM,
	POD_RESTART_HIGH,
	CPU_SATURATION,
	MEMORY_SATURATION,
	PAYMENT_DUPLICATE_ATTEMPT,
	PAYMENT_APPROVAL_DELAY_HIGH,
	PAYMENT_STATE_TRANSITION_ERROR,
	OBSERVABILITY_SOURCE_DOWN,
	UNKNOWN
}
