package com.fintech.sre.agent.evidence;

public enum EvidenceSource {
	INCIDENT_REQUEST,
	SCENARIO_MATCHER,
	RUNBOOK_SELECTOR,
	POSTMORTEM_RETRIEVAL,
	IMPROVEMENT_RETRIEVAL,
	PREVENTIVE_DESIGN_RETRIEVAL,
	RAG_RETRIEVAL,
	PROMETHEUS,
	LOKI,
	JAEGER,
	MANUAL_INPUT,
	LOCAL_STUB,
	UNKNOWN
}
