{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-validation-test",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-test-4.0.6.jar",
          "url": "spring-boot-starter-validation-test-4.0.6.jar",
          "size": 4770,
          "sha512": "f2ad2e950d6f7cd78881aa6b52be1d8ebbf110cf55c9ca1d20124c4a11fde952cef847802fea1e9227b2690038e4bd25305379f41ca37de5e61c8e25381fbdb7",
          "sha256": "f5c5076541cf716a493e8745421e800f1e044d9bbb4bb7a9b8391b3db864c2f7",
          "sha1": "a0d1e9d47ebcd18b3f5570eed1325d703a9586c2",
          "md5": "6ddc48f41b005e3b75744cb9327d9d01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-test-4.0.6.jar",
          "url": "spring-boot-starter-validation-test-4.0.6.jar",
          "size": 4770,
          "sha512": "f2ad2e950d6f7cd78881aa6b52be1d8ebbf110cf55c9ca1d20124c4a11fde952cef847802fea1e9227b2690038e4bd25305379f41ca37de5e61c8e25381fbdb7",
          "sha256": "f5c5076541cf716a493e8745421e800f1e044d9bbb4bb7a9b8391b3db864c2f7",
          "sha1": "a0d1e9d47ebcd18b3f5570eed1325d703a9586c2",
          "md5": "6ddc48f41b005e3b75744cb9327d9d01"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-test-4.0.6-javadoc.jar",
          "url": "spring-boot-starter-validation-test-4.0.6-javadoc.jar",
          "size": 4770,
          "sha512": "f2ad2e950d6f7cd78881aa6b52be1d8ebbf110cf55c9ca1d20124c4a11fde952cef847802fea1e9227b2690038e4bd25305379f41ca37de5e61c8e25381fbdb7",
          "sha256": "f5c5076541cf716a493e8745421e800f1e044d9bbb4bb7a9b8391b3db864c2f7",
          "sha1": "a0d1e9d47ebcd18b3f5570eed1325d703a9586c2",
          "md5": "6ddc48f41b005e3b75744cb9327d9d01"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-test-4.0.6-sources.jar",
          "url": "spring-boot-starter-validation-test-4.0.6-sources.jar",
          "size": 4770,
          "sha512": "f2ad2e950d6f7cd78881aa6b52be1d8ebbf110cf55c9ca1d20124c4a11fde952cef847802fea1e9227b2690038e4bd25305379f41ca37de5e61c8e25381fbdb7",
          "sha256": "f5c5076541cf716a493e8745421e800f1e044d9bbb4bb7a9b8391b3db864c2f7",
          "sha1": "a0d1e9d47ebcd18b3f5570eed1325d703a9586c2",
          "md5": "6ddc48f41b005e3b75744cb9327d9d01"
        }
      ]
    }
  ]
}
