{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-webflux-test",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson-test",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webflux-test",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webtestclient",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-test",
          "version": {
            "requires": "3.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webflux-test-4.0.6.jar",
          "url": "spring-boot-starter-webflux-test-4.0.6.jar",
          "size": 4763,
          "sha512": "25071d07daf2a457126804bc12936c5c4085a075c50ff36c24e891baca157acdf66870f64b7c4fc7bc2650ae939eda633179b47e00aff6a2a2e5215f012aef34",
          "sha256": "ebd8747a322389f43f6bb2b304eb9d74cb70c9b483de97eeb7aa92d791e30210",
          "sha1": "2e38641271e0bd6071ddcb208f3532ffae35506d",
          "md5": "d8fc54e6b044294f57b451c7f93d83cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson-test",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webflux-test",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webtestclient",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-test",
          "version": {
            "requires": "3.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webflux-test-4.0.6.jar",
          "url": "spring-boot-starter-webflux-test-4.0.6.jar",
          "size": 4763,
          "sha512": "25071d07daf2a457126804bc12936c5c4085a075c50ff36c24e891baca157acdf66870f64b7c4fc7bc2650ae939eda633179b47e00aff6a2a2e5215f012aef34",
          "sha256": "ebd8747a322389f43f6bb2b304eb9d74cb70c9b483de97eeb7aa92d791e30210",
          "sha1": "2e38641271e0bd6071ddcb208f3532ffae35506d",
          "md5": "d8fc54e6b044294f57b451c7f93d83cb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-test-4.0.6-javadoc.jar",
          "url": "spring-boot-starter-webflux-test-4.0.6-javadoc.jar",
          "size": 4763,
          "sha512": "25071d07daf2a457126804bc12936c5c4085a075c50ff36c24e891baca157acdf66870f64b7c4fc7bc2650ae939eda633179b47e00aff6a2a2e5215f012aef34",
          "sha256": "ebd8747a322389f43f6bb2b304eb9d74cb70c9b483de97eeb7aa92d791e30210",
          "sha1": "2e38641271e0bd6071ddcb208f3532ffae35506d",
          "md5": "d8fc54e6b044294f57b451c7f93d83cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-test-4.0.6-sources.jar",
          "url": "spring-boot-starter-webflux-test-4.0.6-sources.jar",
          "size": 4763,
          "sha512": "25071d07daf2a457126804bc12936c5c4085a075c50ff36c24e891baca157acdf66870f64b7c4fc7bc2650ae939eda633179b47e00aff6a2a2e5215f012aef34",
          "sha256": "ebd8747a322389f43f6bb2b304eb9d74cb70c9b483de97eeb7aa92d791e30210",
          "sha1": "2e38641271e0bd6071ddcb208f3532ffae35506d",
          "md5": "d8fc54e6b044294f57b451c7f93d83cb"
        }
      ]
    }
  ]
}
