package com.fintech.sre.agent.decision.action;

public enum ActionType {
	APPLY_RATE_LIMIT,
	SCALE_OUT_WORKER,
	SCALE_IN_WORKER,
	PAUSE_ROLLOUT,
	RESTART_POD,
	RETRY_OPERATION,
	CIRCUIT_BREAKER_OPEN,
	DISABLE_IDEMPOTENCY,
	BYPASS_IDEMPOTENCY_CHECK,
	SKIP_DUPLICATE_CHECK,
	FORCE_PAYMENT_STATE_CHANGE
}
