package com.fintech.sre.agent.runtime.readiness;

public enum ActionAdmissionReadinessScope {
	VERIFICATION_READINESS,
	ACTION_TYPE,
	BLAST_RADIUS,
	ROLLBACK_BOUNDARY,
	VERIFICATION_BOUNDARY,
	HUMAN_APPROVAL,
	PAYMENT_SAFETY,
	LIFECYCLE_RISK,
	LIFECYCLE_UNCERTAINTY,
	RUNTIME_READINESS,
	OPERATOR_VIEW
}
