package com.fintech.sre.agent.runtime.readiness;

public enum ActionAdmissionReadinessReason {
	READY_VERIFICATION,
	PARTIAL_VERIFICATION,
	NOT_READY_VERIFICATION,
	UNRELIABLE_VERIFICATION,
	BLOCKED_VERIFICATION,
	MISSING_ACTION_TYPE,
	MISSING_BLAST_RADIUS_BOUNDARY,
	MISSING_ROLLBACK_BINDING,
	MISSING_VERIFICATION_BINDING,
	MISSING_HUMAN_APPROVAL_REQUIREMENT,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	LIFECYCLE_UNCERTAINTY,
	UNKNOWN
}
