package com.fintech.sre.agent.runtime.readiness;

public enum ApprovalReadinessScope {
	RECOMMENDATION_READINESS,
	OPERATOR_CONTEXT,
	HUMAN_APPROVAL,
	PAYMENT_SAFETY,
	LIFECYCLE_RISK,
	LIFECYCLE_UNCERTAINTY,
	RUNTIME_READINESS,
	OPERATOR_VIEW
}
