package com.fintech.sre.agent.runtime.readiness;

public enum ApprovalReadinessReason {
	READY_RECOMMENDATION,
	PARTIAL_RECOMMENDATION,
	NOT_READY_RECOMMENDATION,
	UNRELIABLE_RECOMMENDATION,
	BLOCKED_RECOMMENDATION,
	MISSING_OPERATOR_CONTEXT,
	MISSING_HUMAN_APPROVAL_REQUIREMENT,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	LIFECYCLE_UNCERTAINTY,
	UNKNOWN
}
