package com.fintech.sre.agent.runtime.readiness;

public enum RecommendationReadinessReason {
	HIGH_RECOMMENDATION_RELIABILITY,
	MEDIUM_RECOMMENDATION_RELIABILITY,
	LOW_RECOMMENDATION_RELIABILITY,
	UNRELIABLE_RECOMMENDATION_RELIABILITY,
	BLOCKED_RECOMMENDATION_RELIABILITY,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	LIFECYCLE_UNCERTAINTY,
	UNKNOWN
}
