package com.fintech.sre.agent.runtime.readiness;

public enum VerificationReadinessScope {
	APPROVAL_READINESS,
	VERIFICATION_BOUNDARY,
	VERIFICATION_EVIDENCE,
	ROLLBACK_BOUNDARY,
	PAYMENT_SAFETY,
	LIFECYCLE_RISK,
	LIFECYCLE_UNCERTAINTY,
	RUNTIME_READINESS,
	OPERATOR_VIEW
}
