package com.fintech.sre.agent.runtime.readiness;

public enum VerificationReadinessReason {
	READY_APPROVAL,
	PARTIAL_APPROVAL,
	NOT_READY_APPROVAL,
	UNRELIABLE_APPROVAL,
	BLOCKED_APPROVAL,
	MISSING_VERIFICATION_BINDING,
	MISSING_VERIFICATION_EVIDENCE_REQUIREMENT,
	MISSING_ROLLBACK_BINDING,
	PAYMENT_SAFETY_UNCERTAINTY,
	CRITICAL_LIFECYCLE_RISK,
	LIFECYCLE_UNCERTAINTY,
	UNKNOWN
}
