{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webflux",
    "version": "7.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.7"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webflux-7.0.7.jar",
          "url": "spring-webflux-7.0.7.jar",
          "size": 1021295,
          "sha512": "862d3a9c3c65fcbd3f8359ba732ed10b26470ddb1603559143655f08b89dc22cd11a9e0276558ad36aa53bf4b69cdfe8c6dce724631b40db28ef3db95a54865b",
          "sha256": "cc669b9c9455b12a2094185fc31107b9c034226d1ffc3e25a9db33eb4f468634",
          "sha1": "82c4539a4db9b3a6b50b181453b4107d86e4282e",
          "md5": "12f60097ff9b37cc07692f0c66f61ee1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.7"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webflux-7.0.7.jar",
          "url": "spring-webflux-7.0.7.jar",
          "size": 1021295,
          "sha512": "862d3a9c3c65fcbd3f8359ba732ed10b26470ddb1603559143655f08b89dc22cd11a9e0276558ad36aa53bf4b69cdfe8c6dce724631b40db28ef3db95a54865b",
          "sha256": "cc669b9c9455b12a2094185fc31107b9c034226d1ffc3e25a9db33eb4f468634",
          "sha1": "82c4539a4db9b3a6b50b181453b4107d86e4282e",
          "md5": "12f60097ff9b37cc07692f0c66f61ee1"
        }
      ]
    }
  ]
}
