package com.fintech.sre.agent.incident.lifecycle;

public enum IncidentTransitionReason {
	ALERT_RECEIVED,
	HUMAN_INVESTIGATION_STARTED,
	MITIGATION_IN_PROGRESS,
	VERIFICATION_PARTIAL,
	VERIFICATION_SUCCESS,
	REGRESSION_DETECTED,
	NEW_SYMPTOM_DETECTED,
	MANUAL_ESCALATION,
	MANUAL_REOPEN,
	STABILIZATION_WINDOW_STARTED,
	INCIDENT_RESOLVED
}
