{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-reactor",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-reactor-4.0.6.jar",
          "url": "spring-boot-reactor-4.0.6.jar",
          "size": 11968,
          "sha512": "0697e1f89b8bae36d500317efb729f1f5fd8d43637c70e332280f7bde23f3091437465b42044ec7bb7718e52c6868dbc49ed25ca51fb40bf3c4ca5402a28f1c5",
          "sha256": "898d6216d115be70da411526ce79e88b4284d71cd5eeac5abf242ed78623f8d1",
          "sha1": "506c4920d9e7db6d6e7fd8bdcc92a533cad57a31",
          "md5": "fb0bc61cca882ded6fe8653f9a249a2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-reactor-4.0.6.jar",
          "url": "spring-boot-reactor-4.0.6.jar",
          "size": 11968,
          "sha512": "0697e1f89b8bae36d500317efb729f1f5fd8d43637c70e332280f7bde23f3091437465b42044ec7bb7718e52c6868dbc49ed25ca51fb40bf3c4ca5402a28f1c5",
          "sha256": "898d6216d115be70da411526ce79e88b4284d71cd5eeac5abf242ed78623f8d1",
          "sha1": "506c4920d9e7db6d6e7fd8bdcc92a533cad57a31",
          "md5": "fb0bc61cca882ded6fe8653f9a249a2c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-reactor-4.0.6-javadoc.jar",
          "url": "spring-boot-reactor-4.0.6-javadoc.jar",
          "size": 121980,
          "sha512": "d3cb34f8ae9be3844ac6b207043827854a709c6b1ed780f3ef02ed45ca8a7a49ff649f6565a2fb2caf24a7d21d737b83e8462746bd51133cbaddf6554f146120",
          "sha256": "e159b1f357bd2a110bf31ec0253dda48ffbe95b2a2987c035273e63cef47184b",
          "sha1": "0396ef5f1cfdde20552197f2e00474d9870a0343",
          "md5": "62a780273c02d8156dc9daacbbc8fad3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-reactor-4.0.6-sources.jar",
          "url": "spring-boot-reactor-4.0.6-sources.jar",
          "size": 10936,
          "sha512": "c6bfbd15ef720b663c9c805a52161edbddaa8b235e0b4f81fe4804c805c3e1d9d71ff81b314e7b4c0add6d8bd81cb371ac7a4f916b3c654d66311ed2f4aaed68",
          "sha256": "347c4cb6a36c72233cecf1f0da2261bf33eafee33132b3dd0adcc57b7cbfb11d",
          "sha1": "d680b80c0a66078997f98b91a46b0db496048ba9",
          "md5": "c65e5749f141377d8157ca9cba74d745"
        }
      ]
    }
  ]
}
