{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-webflux",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-reactor",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webflux",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webflux-4.0.6.jar",
          "url": "spring-boot-starter-webflux-4.0.6.jar",
          "size": 4756,
          "sha512": "8e34b5ca7ae5fb4e2a835515a2158dfee5f730f1a2f349c06837f28e996497fe0da4a221d81b7bcf9364b02d10dca8855d1d30175ac9c161a01fa7507a833eed",
          "sha256": "a40a9090818f65deeb80565d1c7fa48734f1a0119a92594df339d5d000fa17a6",
          "sha1": "df4370b1c7ded21522f3f4c0f4196e0cc5a7ac84",
          "md5": "ec9406606f8efd7f07cdca847704217c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-reactor",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webflux",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webflux-4.0.6.jar",
          "url": "spring-boot-starter-webflux-4.0.6.jar",
          "size": 4756,
          "sha512": "8e34b5ca7ae5fb4e2a835515a2158dfee5f730f1a2f349c06837f28e996497fe0da4a221d81b7bcf9364b02d10dca8855d1d30175ac9c161a01fa7507a833eed",
          "sha256": "a40a9090818f65deeb80565d1c7fa48734f1a0119a92594df339d5d000fa17a6",
          "sha1": "df4370b1c7ded21522f3f4c0f4196e0cc5a7ac84",
          "md5": "ec9406606f8efd7f07cdca847704217c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-4.0.6-javadoc.jar",
          "url": "spring-boot-starter-webflux-4.0.6-javadoc.jar",
          "size": 4756,
          "sha512": "8e34b5ca7ae5fb4e2a835515a2158dfee5f730f1a2f349c06837f28e996497fe0da4a221d81b7bcf9364b02d10dca8855d1d30175ac9c161a01fa7507a833eed",
          "sha256": "a40a9090818f65deeb80565d1c7fa48734f1a0119a92594df339d5d000fa17a6",
          "sha1": "df4370b1c7ded21522f3f4c0f4196e0cc5a7ac84",
          "md5": "ec9406606f8efd7f07cdca847704217c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-4.0.6-sources.jar",
          "url": "spring-boot-starter-webflux-4.0.6-sources.jar",
          "size": 4756,
          "sha512": "8e34b5ca7ae5fb4e2a835515a2158dfee5f730f1a2f349c06837f28e996497fe0da4a221d81b7bcf9364b02d10dca8855d1d30175ac9c161a01fa7507a833eed",
          "sha256": "a40a9090818f65deeb80565d1c7fa48734f1a0119a92594df339d5d000fa17a6",
          "sha1": "df4370b1c7ded21522f3f4c0f4196e0cc5a7ac84",
          "md5": "ec9406606f8efd7f07cdca847704217c"
        }
      ]
    }
  ]
}
