{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-micrometer-metrics-test",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-micrometer-metrics",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-micrometer-metrics-test",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-micrometer-metrics-test-4.0.6.jar",
          "url": "spring-boot-starter-micrometer-metrics-test-4.0.6.jar",
          "size": 4753,
          "sha512": "652d04e7fbc732686713c9a1f7445040d16fa35c1d7ac0123f5e1f217b532ec3a766a3d7b56d38b48d83c0beb58006ed6a2f71e639c5c2472debbaa0def0d110",
          "sha256": "f49d372de4fbceb75a6eaa28ce3a207f549ed879ec2258f346bb55c83ffc1e4a",
          "sha1": "98428630b2df376b4ae78100f13b314630d6a03e",
          "md5": "bd1010b199bcf39185175fc855b9766b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-micrometer-metrics",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-micrometer-metrics-test",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-micrometer-metrics-test-4.0.6.jar",
          "url": "spring-boot-starter-micrometer-metrics-test-4.0.6.jar",
          "size": 4753,
          "sha512": "652d04e7fbc732686713c9a1f7445040d16fa35c1d7ac0123f5e1f217b532ec3a766a3d7b56d38b48d83c0beb58006ed6a2f71e639c5c2472debbaa0def0d110",
          "sha256": "f49d372de4fbceb75a6eaa28ce3a207f549ed879ec2258f346bb55c83ffc1e4a",
          "sha1": "98428630b2df376b4ae78100f13b314630d6a03e",
          "md5": "bd1010b199bcf39185175fc855b9766b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-micrometer-metrics-test-4.0.6-javadoc.jar",
          "url": "spring-boot-starter-micrometer-metrics-test-4.0.6-javadoc.jar",
          "size": 4753,
          "sha512": "652d04e7fbc732686713c9a1f7445040d16fa35c1d7ac0123f5e1f217b532ec3a766a3d7b56d38b48d83c0beb58006ed6a2f71e639c5c2472debbaa0def0d110",
          "sha256": "f49d372de4fbceb75a6eaa28ce3a207f549ed879ec2258f346bb55c83ffc1e4a",
          "sha1": "98428630b2df376b4ae78100f13b314630d6a03e",
          "md5": "bd1010b199bcf39185175fc855b9766b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-micrometer-metrics-test-4.0.6-sources.jar",
          "url": "spring-boot-starter-micrometer-metrics-test-4.0.6-sources.jar",
          "size": 4753,
          "sha512": "652d04e7fbc732686713c9a1f7445040d16fa35c1d7ac0123f5e1f217b532ec3a766a3d7b56d38b48d83c0beb58006ed6a2f71e639c5c2472debbaa0def0d110",
          "sha256": "f49d372de4fbceb75a6eaa28ce3a207f549ed879ec2258f346bb55c83ffc1e4a",
          "sha1": "98428630b2df376b4ae78100f13b314630d6a03e",
          "md5": "bd1010b199bcf39185175fc855b9766b"
        }
      ]
    }
  ]
}
