{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-reactor-netty",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-reactor",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-reactor-netty",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-reactor-netty-4.0.6.jar",
          "url": "spring-boot-starter-reactor-netty-4.0.6.jar",
          "size": 4743,
          "sha512": "0e074cfe3fbe68b3258d632bfb5dd0287719dc7003935ede6b426f72898d530a3cfd0510331710428f14863c2bcd23d6429ba37d78eba24438fd6c95b75789e8",
          "sha256": "63f3ab4cea4f478ebacb1d7b347c4ced345f6050b4698e9c19ed1eaf9236555c",
          "sha1": "dbe5c0c7a8156c92eb81a8b60526671dfa0b4ca9",
          "md5": "3f89551d3d41dbde919f44b0d461886f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-reactor",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-reactor-netty",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-reactor-netty-4.0.6.jar",
          "url": "spring-boot-starter-reactor-netty-4.0.6.jar",
          "size": 4743,
          "sha512": "0e074cfe3fbe68b3258d632bfb5dd0287719dc7003935ede6b426f72898d530a3cfd0510331710428f14863c2bcd23d6429ba37d78eba24438fd6c95b75789e8",
          "sha256": "63f3ab4cea4f478ebacb1d7b347c4ced345f6050b4698e9c19ed1eaf9236555c",
          "sha1": "dbe5c0c7a8156c92eb81a8b60526671dfa0b4ca9",
          "md5": "3f89551d3d41dbde919f44b0d461886f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-reactor-netty-4.0.6-javadoc.jar",
          "url": "spring-boot-starter-reactor-netty-4.0.6-javadoc.jar",
          "size": 4743,
          "sha512": "0e074cfe3fbe68b3258d632bfb5dd0287719dc7003935ede6b426f72898d530a3cfd0510331710428f14863c2bcd23d6429ba37d78eba24438fd6c95b75789e8",
          "sha256": "63f3ab4cea4f478ebacb1d7b347c4ced345f6050b4698e9c19ed1eaf9236555c",
          "sha1": "dbe5c0c7a8156c92eb81a8b60526671dfa0b4ca9",
          "md5": "3f89551d3d41dbde919f44b0d461886f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-reactor-netty-4.0.6-sources.jar",
          "url": "spring-boot-starter-reactor-netty-4.0.6-sources.jar",
          "size": 4743,
          "sha512": "0e074cfe3fbe68b3258d632bfb5dd0287719dc7003935ede6b426f72898d530a3cfd0510331710428f14863c2bcd23d6429ba37d78eba24438fd6c95b75789e8",
          "sha256": "63f3ab4cea4f478ebacb1d7b347c4ced345f6050b4698e9c19ed1eaf9236555c",
          "sha1": "dbe5c0c7a8156c92eb81a8b60526671dfa0b4ca9",
          "md5": "3f89551d3d41dbde919f44b0d461886f"
        }
      ]
    }
  ]
}
