{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-actuator-test",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-micrometer-metrics-test",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-test-4.0.6.jar",
          "url": "spring-boot-starter-actuator-test-4.0.6.jar",
          "size": 4809,
          "sha512": "acbc0710f4ce21f84317b5e23b42837d6053ea4627c5f55f91dc98e2f9f0aa134d78ed26347560f8f06686336e7b1d81e320e083ee649d49af832186a6687d5d",
          "sha256": "31c5613ae6e4d0fb2075184b504f91e4ef8e8d8aa546d99ef59d5582c571470e",
          "sha1": "4bc3894c96b19d3b6a7caaa8fb58dc9682114dcd",
          "md5": "3faeef9f8b060c0d053a4004b3221af4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-micrometer-metrics-test",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-test-4.0.6.jar",
          "url": "spring-boot-starter-actuator-test-4.0.6.jar",
          "size": 4809,
          "sha512": "acbc0710f4ce21f84317b5e23b42837d6053ea4627c5f55f91dc98e2f9f0aa134d78ed26347560f8f06686336e7b1d81e320e083ee649d49af832186a6687d5d",
          "sha256": "31c5613ae6e4d0fb2075184b504f91e4ef8e8d8aa546d99ef59d5582c571470e",
          "sha1": "4bc3894c96b19d3b6a7caaa8fb58dc9682114dcd",
          "md5": "3faeef9f8b060c0d053a4004b3221af4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-test-4.0.6-javadoc.jar",
          "url": "spring-boot-starter-actuator-test-4.0.6-javadoc.jar",
          "size": 4809,
          "sha512": "acbc0710f4ce21f84317b5e23b42837d6053ea4627c5f55f91dc98e2f9f0aa134d78ed26347560f8f06686336e7b1d81e320e083ee649d49af832186a6687d5d",
          "sha256": "31c5613ae6e4d0fb2075184b504f91e4ef8e8d8aa546d99ef59d5582c571470e",
          "sha1": "4bc3894c96b19d3b6a7caaa8fb58dc9682114dcd",
          "md5": "3faeef9f8b060c0d053a4004b3221af4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-test-4.0.6-sources.jar",
          "url": "spring-boot-starter-actuator-test-4.0.6-sources.jar",
          "size": 4809,
          "sha512": "acbc0710f4ce21f84317b5e23b42837d6053ea4627c5f55f91dc98e2f9f0aa134d78ed26347560f8f06686336e7b1d81e320e083ee649d49af832186a6687d5d",
          "sha256": "31c5613ae6e4d0fb2075184b504f91e4ef8e8d8aa546d99ef59d5582c571470e",
          "sha1": "4bc3894c96b19d3b6a7caaa8fb58dc9682114dcd",
          "md5": "3faeef9f8b060c0d053a4004b3221af4"
        }
      ]
    }
  ]
}
